### ISSUE TITLE
[Storage Provider Bounty Issue] Power multiplication for normal deals and verified deals

### ISSUE THREAD

**Issue by vnessasgrt** [filecoin-project/community#311]
## 1. Proposed issue:

Power multiplication for normal deals and verified deals

## 2. Why is this issue important?

The random data equaling unverified data is hard to comprehend from a logical perspective

## 3. Tasks

- [ ] Create a Document/Graphic on how to help clients apprehend the power multiplication for normal deal and verified deals. 
- [ ] Explain the difference and how it is calculated 
- [ ] Explain how the real data happens
